// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFMZoNwEWNqCOfUezoSB-TewpOBUfX98',
    appId: '1:909481590933:web:6e6a7dbb155d1fd6a5db9c',
    messagingSenderId: '909481590933',
    projectId: 'mgoalindo---app',
    authDomain: 'mgoalindo---app.firebaseapp.com',
    databaseURL: 'https://mgoalindo---app-default-rtdb.firebaseio.com',
    storageBucket: 'mgoalindo---app.appspot.com',
    measurementId: 'G-70N3LKRGP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAMHpEi9oAKdnUbcQW6mPm5s2XXix5Rs',
    appId: '1:909481590933:android:9ceb93a5c70a0affa5db9c',
    messagingSenderId: '909481590933',
    projectId: 'mgoalindo---app',
    databaseURL: 'https://mgoalindo---app-default-rtdb.firebaseio.com',
    storageBucket: 'mgoalindo---app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKfGzpWrbg-voCWx0-nhobhpJj5S_ek8',
    appId: '1:909481590933:ios:c00e29c66534f097a5db9c',
    messagingSenderId: '909481590933',
    projectId: 'mgoalindo---app',
    databaseURL: 'https://mgoalindo---app-default-rtdb.firebaseio.com',
    storageBucket: 'mgoalindo---app.appspot.com',
    androidClientId: '909481590933-rivh0pi8loiguu7t6v18s2eogpi23fle.apps.googleusercontent.com',
    iosClientId: '909481590933-h9maj942pk26k4umccdbqdon5ncteqnf.apps.googleusercontent.com',
    iosBundleId: 'com.akujuara.akuJuara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADKfGzpWrbg-voCWx0-nhobhpJj5S_ek8',
    appId: '1:909481590933:ios:c00e29c66534f097a5db9c',
    messagingSenderId: '909481590933',
    projectId: 'mgoalindo---app',
    databaseURL: 'https://mgoalindo---app-default-rtdb.firebaseio.com',
    storageBucket: 'mgoalindo---app.appspot.com',
    androidClientId: '909481590933-rivh0pi8loiguu7t6v18s2eogpi23fle.apps.googleusercontent.com',
    iosClientId: '909481590933-h9maj942pk26k4umccdbqdon5ncteqnf.apps.googleusercontent.com',
    iosBundleId: 'com.akujuara.akuJuara',
  );
}
